"""Make team_id nullable in slack_installations

Revision ID: 0b5f27912298
Revises: c0a8833b8808
Create Date: 2026-01-16 18:07:43.266035

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b5f27912298"
down_revision: str | Sequence[str] | None = "c0a8833b8808"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slack_installations", schema=None) as batch_op:
        batch_op.alter_column("team_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("slack_installations", schema=None) as batch_op:
        batch_op.alter_column("team_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
