"""Add Slack OAuth tables

Revision ID: c0a8833b8808
Revises: 6cf1a0c5fa64
Create Date: 2026-01-16 16:32:30.329114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a8833b8808'
down_revision: Union[str, Sequence[str], None] = '6cf1a0c5fa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('enterprise_id', sa.String(), nullable=True),
    sa.Column('bot_token', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('bot_user_id', sa.String(), nullable=True),
    sa.Column('installer_user_id', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('is_enterprise_install', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slack_installations_id'), 'slack_installations', ['id'], unique=False)
    op.create_index(op.f('ix_slack_installations_team_id'), 'slack_installations', ['team_id'], unique=False)
    op.create_table('slack_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_index(op.f('ix_slack_states_id'), 'slack_states', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_states_id'), table_name='slack_states')
    op.drop_table('slack_states')
    op.drop_index(op.f('ix_slack_installations_team_id'), table_name='slack_installations')
    op.drop_index(op.f('ix_slack_installations_id'), table_name='slack_installations')
    op.drop_table('slack_installations')
    # ### end Alembic commands ###
